### ISSUE TITLE
Docs url broken

### ISSUE THREAD

**Issue by MakerDockio** [austinscreations/OXRS-AC-SecurityMonitor-ESP32-FW#1]
Docs URL on README.md not linking to docs getting a 404

**Comment by austinscreations** [comment]
thats cuz i haven't made the docs yet. eventually i assure ya i'll get there.

**Comment by sumnerboy12** [comment]
1yr later...

**Comment by austinscreations** [comment]
as far as i can tell - i've fixed all links.
i'll close for now
