### ISSUE TITLE
Add command to query "all" sensor state

### ISSUE THREAD

**Issue by sumnerboy12** [austinscreations/OXRS-AC-SecurityMonitor-ESP32-FW#6]
Useful for a home automation platform/system to initialise its own state on startup. Fire off a "query all" command and it will get back the current state of all sensors.

Have to be careful that this doesn't trigger automations or rules tho. Should these state updates be published to a different topic, rather than the standard `stat/<deviceid>`? 

Related to https://github.com/OXRS-IO/OXRS-IO-StateMonitor-ESP-FW/issues/41

**Comment by austinscreations** [comment]
maybe `query/<deviceid>`

**Comment by sumnerboy12** [comment]
Most of the logic has been implemented in https://github.com/OXRS-IO/OXRS-IO-IOHandler-ESP32-LIB/pull/5
